################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
simplelink/source/device.obj: D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source/device.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"D:/TI/ccs/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me --opt_for_speed=2 --include_path="D:/TI/ccs/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/include" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/ti/sysbios/posix" --include_path="F:/Embedded_System/PROJECT/http_serverCC3100/wifi_node_ap_tirtos" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111/examples/boards/ek-tm4c1294xl-boostxl-senshub/drivers" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111/examples/boards/ek-tm4c1294xl-boostxl-senshub" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/TivaWare_C_Series-2.1.1.71b" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/include" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/TivaWare_C_Series-2.1.1.71b/" --include_path="F:/Embedded_System/PROJECT/http_serverCC3100/wifi_node_ap_tirtos/" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/include" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source" -g --gcc --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --define=_USE_CLI_ --define=ccs="ccs" --define="TIRTOS" --diag_wrap=off --diag_warning=225 --display_error_number --preproc_with_compile --preproc_dependency="simplelink/source/device.d" --obj_directory="simplelink/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

simplelink/source/driver.obj: D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source/driver.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"D:/TI/ccs/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me --opt_for_speed=2 --include_path="D:/TI/ccs/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/include" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/ti/sysbios/posix" --include_path="F:/Embedded_System/PROJECT/http_serverCC3100/wifi_node_ap_tirtos" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111/examples/boards/ek-tm4c1294xl-boostxl-senshub/drivers" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111/examples/boards/ek-tm4c1294xl-boostxl-senshub" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/TivaWare_C_Series-2.1.1.71b" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/include" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/TivaWare_C_Series-2.1.1.71b/" --include_path="F:/Embedded_System/PROJECT/http_serverCC3100/wifi_node_ap_tirtos/" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/include" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source" -g --gcc --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --define=_USE_CLI_ --define=ccs="ccs" --define="TIRTOS" --diag_wrap=off --diag_warning=225 --display_error_number --preproc_with_compile --preproc_dependency="simplelink/source/driver.d" --obj_directory="simplelink/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

simplelink/source/flowcont.obj: D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source/flowcont.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"D:/TI/ccs/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me --opt_for_speed=2 --include_path="D:/TI/ccs/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/include" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/ti/sysbios/posix" --include_path="F:/Embedded_System/PROJECT/http_serverCC3100/wifi_node_ap_tirtos" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111/examples/boards/ek-tm4c1294xl-boostxl-senshub/drivers" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111/examples/boards/ek-tm4c1294xl-boostxl-senshub" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/TivaWare_C_Series-2.1.1.71b" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/include" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/TivaWare_C_Series-2.1.1.71b/" --include_path="F:/Embedded_System/PROJECT/http_serverCC3100/wifi_node_ap_tirtos/" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/include" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source" -g --gcc --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --define=_USE_CLI_ --define=ccs="ccs" --define="TIRTOS" --diag_wrap=off --diag_warning=225 --display_error_number --preproc_with_compile --preproc_dependency="simplelink/source/flowcont.d" --obj_directory="simplelink/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

simplelink/source/fs.obj: D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source/fs.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"D:/TI/ccs/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me --opt_for_speed=2 --include_path="D:/TI/ccs/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/include" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/ti/sysbios/posix" --include_path="F:/Embedded_System/PROJECT/http_serverCC3100/wifi_node_ap_tirtos" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111/examples/boards/ek-tm4c1294xl-boostxl-senshub/drivers" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111/examples/boards/ek-tm4c1294xl-boostxl-senshub" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/TivaWare_C_Series-2.1.1.71b" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/include" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/TivaWare_C_Series-2.1.1.71b/" --include_path="F:/Embedded_System/PROJECT/http_serverCC3100/wifi_node_ap_tirtos/" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/include" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source" -g --gcc --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --define=_USE_CLI_ --define=ccs="ccs" --define="TIRTOS" --diag_wrap=off --diag_warning=225 --display_error_number --preproc_with_compile --preproc_dependency="simplelink/source/fs.d" --obj_directory="simplelink/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

simplelink/source/netapp.obj: D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source/netapp.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"D:/TI/ccs/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me --opt_for_speed=2 --include_path="D:/TI/ccs/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/include" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/ti/sysbios/posix" --include_path="F:/Embedded_System/PROJECT/http_serverCC3100/wifi_node_ap_tirtos" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111/examples/boards/ek-tm4c1294xl-boostxl-senshub/drivers" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111/examples/boards/ek-tm4c1294xl-boostxl-senshub" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/TivaWare_C_Series-2.1.1.71b" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/include" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/TivaWare_C_Series-2.1.1.71b/" --include_path="F:/Embedded_System/PROJECT/http_serverCC3100/wifi_node_ap_tirtos/" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/include" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source" -g --gcc --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --define=_USE_CLI_ --define=ccs="ccs" --define="TIRTOS" --diag_wrap=off --diag_warning=225 --display_error_number --preproc_with_compile --preproc_dependency="simplelink/source/netapp.d" --obj_directory="simplelink/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

simplelink/source/netcfg.obj: D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source/netcfg.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"D:/TI/ccs/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me --opt_for_speed=2 --include_path="D:/TI/ccs/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/include" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/ti/sysbios/posix" --include_path="F:/Embedded_System/PROJECT/http_serverCC3100/wifi_node_ap_tirtos" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111/examples/boards/ek-tm4c1294xl-boostxl-senshub/drivers" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111/examples/boards/ek-tm4c1294xl-boostxl-senshub" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/TivaWare_C_Series-2.1.1.71b" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/include" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/TivaWare_C_Series-2.1.1.71b/" --include_path="F:/Embedded_System/PROJECT/http_serverCC3100/wifi_node_ap_tirtos/" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/include" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source" -g --gcc --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --define=_USE_CLI_ --define=ccs="ccs" --define="TIRTOS" --diag_wrap=off --diag_warning=225 --display_error_number --preproc_with_compile --preproc_dependency="simplelink/source/netcfg.d" --obj_directory="simplelink/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

simplelink/source/nonos.obj: D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source/nonos.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"D:/TI/ccs/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me --opt_for_speed=2 --include_path="D:/TI/ccs/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/include" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/ti/sysbios/posix" --include_path="F:/Embedded_System/PROJECT/http_serverCC3100/wifi_node_ap_tirtos" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111/examples/boards/ek-tm4c1294xl-boostxl-senshub/drivers" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111/examples/boards/ek-tm4c1294xl-boostxl-senshub" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/TivaWare_C_Series-2.1.1.71b" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/include" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/TivaWare_C_Series-2.1.1.71b/" --include_path="F:/Embedded_System/PROJECT/http_serverCC3100/wifi_node_ap_tirtos/" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/include" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source" -g --gcc --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --define=_USE_CLI_ --define=ccs="ccs" --define="TIRTOS" --diag_wrap=off --diag_warning=225 --display_error_number --preproc_with_compile --preproc_dependency="simplelink/source/nonos.d" --obj_directory="simplelink/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

simplelink/source/socket.obj: D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source/socket.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"D:/TI/ccs/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me --opt_for_speed=2 --include_path="D:/TI/ccs/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/include" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/ti/sysbios/posix" --include_path="F:/Embedded_System/PROJECT/http_serverCC3100/wifi_node_ap_tirtos" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111/examples/boards/ek-tm4c1294xl-boostxl-senshub/drivers" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111/examples/boards/ek-tm4c1294xl-boostxl-senshub" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/TivaWare_C_Series-2.1.1.71b" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/include" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/TivaWare_C_Series-2.1.1.71b/" --include_path="F:/Embedded_System/PROJECT/http_serverCC3100/wifi_node_ap_tirtos/" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/include" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source" -g --gcc --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --define=_USE_CLI_ --define=ccs="ccs" --define="TIRTOS" --diag_wrap=off --diag_warning=225 --display_error_number --preproc_with_compile --preproc_dependency="simplelink/source/socket.d" --obj_directory="simplelink/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

simplelink/source/spawn.obj: D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source/spawn.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"D:/TI/ccs/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me --opt_for_speed=2 --include_path="D:/TI/ccs/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/include" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/ti/sysbios/posix" --include_path="F:/Embedded_System/PROJECT/http_serverCC3100/wifi_node_ap_tirtos" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111/examples/boards/ek-tm4c1294xl-boostxl-senshub/drivers" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111/examples/boards/ek-tm4c1294xl-boostxl-senshub" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/TivaWare_C_Series-2.1.1.71b" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/include" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/TivaWare_C_Series-2.1.1.71b/" --include_path="F:/Embedded_System/PROJECT/http_serverCC3100/wifi_node_ap_tirtos/" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/include" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source" -g --gcc --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --define=_USE_CLI_ --define=ccs="ccs" --define="TIRTOS" --diag_wrap=off --diag_warning=225 --display_error_number --preproc_with_compile --preproc_dependency="simplelink/source/spawn.d" --obj_directory="simplelink/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

simplelink/source/wlan.obj: D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source/wlan.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"D:/TI/ccs/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me --opt_for_speed=2 --include_path="D:/TI/ccs/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/include" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/bios_6_45_02_31/packages/ti/sysbios/posix" --include_path="F:/Embedded_System/PROJECT/http_serverCC3100/wifi_node_ap_tirtos" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111/examples/boards/ek-tm4c1294xl-boostxl-senshub/drivers" --include_path="D:/TI/TivaWare_C_Series-2.1.2.111/examples/boards/ek-tm4c1294xl-boostxl-senshub" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/TivaWare_C_Series-2.1.1.71b" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/include" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source" --include_path="D:/TI/ccs/tirtos_tivac_2_16_01_14/products/TivaWare_C_Series-2.1.1.71b/" --include_path="F:/Embedded_System/PROJECT/http_serverCC3100/wifi_node_ap_tirtos/" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/include" --include_path="D:/TI/CC3100SDK_1.2.0/cc3100-sdk/simplelink/source" -g --gcc --define=PART_TM4C1294NCPDT --define=TARGET_IS_TM4C129_RA1 --define=_USE_CLI_ --define=ccs="ccs" --define="TIRTOS" --diag_wrap=off --diag_warning=225 --display_error_number --preproc_with_compile --preproc_dependency="simplelink/source/wlan.d" --obj_directory="simplelink/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


